package com.zl.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-16T19:47:35.766+08:00
 * Generated source version: 3.2.2
 *
 */
@WebService(targetNamespace = "http://server.zl.com/", name = "sayWebService")
@XmlSeeAlso({ObjectFactory.class})
public interface SayWebService {

    @WebMethod
    @RequestWrapper(localName = "getUserBy", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetUserBy")
    @ResponseWrapper(localName = "getUserByResponse", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetUserByResponse")
    @WebResult(name = "return", targetNamespace = "")
    public com.zl.client.User getUserBy(
        @WebParam(name = "user", targetNamespace = "")
        com.zl.client.User user
    );

    @WebMethod
    @RequestWrapper(localName = "getHollerSay", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetHollerSay")
    @ResponseWrapper(localName = "getHollerSayResponse", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetHollerSayResponse")
    @WebResult(name = "return", targetNamespace = "")
    public java.lang.String getHollerSay(
        @WebParam(name = "arg0", targetNamespace = "")
        java.lang.String arg0
    );

    @WebMethod
    @RequestWrapper(localName = "getSay", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetSay")
    @ResponseWrapper(localName = "getSayResponse", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetSayResponse")
    public void getSay();
}
