
package com.zl.client;

/**
 * Please modify this class to meet your needs
 * This class is not complete
 */

import java.io.File;
import java.net.MalformedURLException;
import java.net.URL;
import javax.xml.namespace.QName;
import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;

/**
 * This class was generated by Apache CXF 3.2.2
 * 2018-03-16T19:47:35.250+08:00
 * Generated source version: 3.2.2
 *
 */
public final class SayWebService_SayWebServiceImplPort_Client {

    private static final QName SERVICE_NAME = new QName("http://server.zl.com/", "SayWebServiceImplService");

    private SayWebService_SayWebServiceImplPort_Client() {
    }

    public static void main(String args[]) throws java.lang.Exception {
        URL wsdlURL = SayWebServiceImplService.WSDL_LOCATION;
        if (args.length > 0 && args[0] != null && !"".equals(args[0])) {
            File wsdlFile = new File(args[0]);
            try {
                if (wsdlFile.exists()) {
                    wsdlURL = wsdlFile.toURI().toURL();
                } else {
                    wsdlURL = new URL(args[0]);
                }
            } catch (MalformedURLException e) {
                e.printStackTrace();
            }
        }

        SayWebServiceImplService ss = new SayWebServiceImplService(wsdlURL, SERVICE_NAME);
        SayWebService port = ss.getSayWebServiceImplPort();

        {
        System.out.println("Invoking getUserBy...");
        com.zl.client.User _getUserBy_user = null;
        com.zl.client.User _getUserBy__return = port.getUserBy(_getUserBy_user);
        System.out.println("getUserBy.result=" + _getUserBy__return);


        }
        {
        System.out.println("Invoking getHollerSay...");
        java.lang.String _getHollerSay_arg0 = "";
        java.lang.String _getHollerSay__return = port.getHollerSay(_getHollerSay_arg0);
        System.out.println("getHollerSay.result=" + _getHollerSay__return);


        }
        {
        System.out.println("Invoking getSay...");
        port.getSay();


        }

        System.exit(0);
    }

}
