
package com.zl.client;

import javax.jws.WebMethod;
import javax.jws.WebParam;
import javax.jws.WebResult;
import javax.jws.WebService;
import javax.xml.bind.annotation.XmlSeeAlso;
import javax.xml.ws.Action;
import javax.xml.ws.RequestWrapper;
import javax.xml.ws.ResponseWrapper;


/**
 * This class was generated by the JAX-WS RI.
 * JAX-WS RI 2.2.9-b130926.1035
 * Generated source version: 2.2
 * 
 */
@WebService(name = "sayServiceImpl", targetNamespace = "http://server.zl.com/")
@XmlSeeAlso({
    ObjectFactory.class
})
public interface SayServiceImpl {


    /**
     * 
     */
    @WebMethod
    @RequestWrapper(localName = "getSay", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetSay")
    @ResponseWrapper(localName = "getSayResponse", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetSayResponse")
    @Action(input = "http://server.zl.com/sayServiceImpl/getSayRequest", output = "http://server.zl.com/sayServiceImpl/getSayResponse")
    public void getSay();

    /**
     * 
     * @param arg0
     * @return
     *     returns java.lang.String
     */
    @WebMethod
    @WebResult(targetNamespace = "")
    @RequestWrapper(localName = "getHollerSay", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetHollerSay")
    @ResponseWrapper(localName = "getHollerSayResponse", targetNamespace = "http://server.zl.com/", className = "com.zl.client.GetHollerSayResponse")
    @Action(input = "http://server.zl.com/sayServiceImpl/getHollerSayRequest", output = "http://server.zl.com/sayServiceImpl/getHollerSayResponse")
    public String getHollerSay(
        @WebParam(name = "arg0", targetNamespace = "")
        String arg0);

}
